### PR TITLE
Update moonlight-common-c and allow user to select video codec

### PR DESCRIPTION
**Pull request by henryfa2**
# Update moonlight-common-c and allow user to select video codec

1) Update moonlight-common-c 
2) Allow user to select video codec used by the application and show a message in case of codec changing, warning user that application should be restarted

### CODE REVIEW

**Comment by sieskei** [comment]
After the latest changes, it stopped working for me.
"Loading Moonlight plugin ..." forever.

**Comment by OneLiberty** [comment]
Could you check the log and post a screen ? (https://github.com/OneLiberty/moonlight-chrome-tizen/discussions/9)

**Comment by sieskei** [comment]
Now I tried quickly through Docker.
**In the browser, I get a white screen after selecting Moonlight.**

In the dev console, I see the following errors:

**Before clicking on Moonlight:**
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (undefined, line 0)`

**After clicking on Moonlight:**
```
[Error] Unhandled Promise Rejection: TypeError: icon.setIconType is not a function. (In 'icon.setIconType(iconType)', 'icon.setIconType' is undefined)
create (shell.js:1856)
_createDropDownButton (shell.js:2903:158)
(anonymous function) (shell.js:2818:1282)
(anonymous function) (shell.js:1202:269)
createTabbedLocation (shell.js:1177:130)
(anonymous function) (shell.js:1485)
sharedInstance (shell.js:81:92)
(anonymous function) (shell.js:8128:596)
_createAppUI (shell.js:8128:2858)
_gotPreferences (shell.js:8120)
getPreferences (shell.js:954)
(anonymous function) (shell.js:8118:180)
```

**Comment by sieskei** [comment]
I don't see any meaningful information.
By the way, I'm using Safari on macOS Sonoma.

**Comment by OneLiberty** [comment]
It doesn't work with safari. 
Try firefox or chrome.

**Comment by sieskei** [comment]
```
Uncaught TypeError: Cannot read property 'getModel' of undefined
    at index.js:17
```

`common.js:128 [updateStatus, common.js] Page loaded.`

`common.js:15 WASM runtime initialized`

`common.js:128 [updateStatus, common.js] RUNNING`

```
index.js:1067 Uncaught ReferenceError: Cannot access 'db' before initialization
    at openIndexDB (index.js:1067)
    at loadHTTPCerts (index.js:1474)
    at moduleDidLoad (index.js:271)
    at Object.onRuntimeInitialized (common.js:19)
    at doRun (moonlight-wasm.js:1)
    at run (moonlight-wasm.js:1)
    at runCaller (moonlight-wasm.js:1)
    at removeRunDependency (moonlight-wasm.js:1)
    at moonlight-wasm.js:1
    at Worker.worker.onmessage (moonlight-wasm.js:1)
```

EDIT:
A quick fix:

Put this in a function and call it from window.onload.
Apparently, the webapis isn't ready at such an early stage.

```
function loadProductInfo() {
  var modelCodePlaceholder = document.getElementById("modelCodePlaceholder");
  if (modelCodePlaceholder) {
  ....
  }
}

function onWindowLoad() {
  ....
  loadProductInfo();
}
```

**Comment by henryfa2** [comment]
> ```
> Uncaught TypeError: Cannot read property 'getModel' of undefined
>     at index.js:17
> ```
> 
> `common.js:128 [updateStatus, common.js] Page loaded.`
> 
> `common.js:15 WASM runtime initialized`
> 
> `common.js:128 [updateStatus, common.js] RUNNING`
> 
> ```
> index.js:1067 Uncaught ReferenceError: Cannot access 'db' before initialization
>     at openIndexDB (index.js:1067)
>     at loadHTTPCerts (index.js:1474)
>     at moduleDidLoad (index.js:271)
>     at Object.onRuntimeInitialized (common.js:19)
>     at doRun (moonlight-wasm.js:1)
>     at run (moonlight-wasm.js:1)
>     at runCaller (moonlight-wasm.js:1)
>     at removeRunDependency (moonlight-wasm.js:1)
>     at moonlight-wasm.js:1
>     at Worker.worker.onmessage (moonlight-wasm.js:1)
> ```

It seems to be a problem with commit "[Added TV Model info on bottom left corner](https://github.com/KyroFrCode/moonlight-chrome-tizen/commit/cc856db65aa04fa171fff2eac9f3c8a3a4edd28a)", not a problem with my PR

**Comment by OneLiberty** [comment]
@henryfa2 indeed ! it is most likely an issue with the [ProductInfo API](https://developer.samsung.com/smarttv/develop/api-references/samsung-product-api-references/productinfo-api.html)

@sieskei 
May i get some info about your TV, this api is supported by TVs since tizen 2.3 so i don't really know what could be the issue. If you can you can try to build the app without [this](https://github.com/KyroFrCode/moonlight-chrome-tizen/commit/cc856db65aa04fa171fff2eac9f3c8a3a4edd28a#diff-4ffd3102aa3b8e181768fa9d4116d0346c61e6f4c9aba7a267bc64aa92c9fadbR170) commit.

**Comment by sieskei** [comment]
I edited the above post, take a look at it.

image

**Pull request merged**
