### PR TITLE
Feat/adding 90 120 144 fps option

### PR DESCRIPTION
**Pull request by susin03**
[feat: adding 90, 120 and 144 fps options to the framerate select](https://github.com/OneLiberty/moonlight-chrome-tizen/commit/a339dbb4cb5268dfea74c739fcefc382d719873f)

[feat: adding 90, 120 and 144 options to the automatic bitrate selecti…](https://github.com/OneLiberty/moonlight-chrome-tizen/commit/8b6ef3184af3c78508b3ac57746c96c86997bd69)

### CODE REVIEW

**Review by LeGeRyChEeSe — APPROVED** [review]
I really need this feature thanks !

**Comment by OneLiberty** [comment]
@susin03 Thanks for the PR, tho before merging, i'd like to have some proof that it is actually supported and working. 
I don't have time to do this, hence why i'm asking you. 
Once done i'll merge it. 

I also saw you setting a bitrate of 120, this will not be supported by most TVs, especially lower end. So it souldn't be available for those. 

EDIT: @LeGeRyChEeSe Have you tested ?

**Comment by LeGeRyChEeSe** [comment]
Hello no i haven’t tested because i don’t know how to build it manually. I opened a discussion for this -> https://github.com/OneLiberty/moonlight-chrome-tizen/discussions/78

**Comment by susin03** [comment]
Hey guys, sorry for the delay on the response.
As for the build part, I couldn't deploy the app because of the certificate error (#37), so the process I did, was get and deploy the Zip version via USB drive, accessing the docker container.
I've tested it on my TV (50QN90C), and it seems to work. About the bitrate, I guess that could be removed, a big reason to it is that the TV's RJ45 ethernet connection is only 100Mbps, so in my case that wasn't actually supported.
The framerate options appears to be working as expected, but I don't have a way to inspect it, for now, the only way that I know to measure the framerate is in the GameBar, which I couldn't activate while in the app.
Please if you have any suggestions, let me know and I'll test it as soon as I can.

**Comment by LeGeRyChEeSe** [comment]
> Hey guys, sorry for the delay on the response. As for the build part, I couldn't deploy the app because of the certificate error (#37), so the process I did, was get and deploy the Zip version via USB drive, accessing the docker container. I've tested it on my TV (50QN90C), and it seems to work. About the bitrate, I guess that could be removed, a big reason to it is that the TV's RJ45 ethernet connection is only 100Mbps, so in my case that wasn't actually supported. The framerate options appears to be working as expected, but I don't have a way to inspect it, for now, the only way that I know to measure the framerate is in the GameBar, which I couldn't activate while in the app. Please if you have any suggestions, let me know and I'll test it as soon as I can.

Same here, I managed to compile the project and install it in the normal way using `sdb` and the tool works perfectly. I don't have a way to check if I have 120FPS on my TV, but in any case I haven't seen any anomaly, I feel like I no longer have any freezing problems since this version.

The Workaround to compile the project is in the answer of this discussion → #78

**Comment by hi-liang** [comment]
> Thanks for the PR, tho before merging, i'd like to have some proof that it is actually supported and working.

FWIW if you run the app with remote debugging, it looks like sending the request for higher frame rate is working to the server (Apollo in my case):

```
[2024-12-20 13:02:17.136]: Info: Display refresh rate [143.998Hz]
[2024-12-20 13:02:17.136]: Info: Requested frame rate [120fps]
```

but tracking window RAF intervals shows that the web app is only rendering at 60FPS, so the video embed is limited to that anyhow. Not sure what can be done about that constraint. 

This was tested on a S90D.

**Comment by susin03** [comment]
> but tracking window RAF intervals shows that the web app is only rendering at 60FPS, so the video embed is limited to that anyhow. Not sure what can be done about that constraint.


Well guys, based on this, I guess that no effort is worth here, I will be abandoning the PR, thank you all for the help!

**Pull request closed without merging**
