### PR TITLE
Fix server codec support checks. Add AV1 support

### PR DESCRIPTION
**Pull request by HnwT**
# Add AV1 support

Changes proposed in this pull request:
- Fix server codec support checks to use `ServerCodecSupportMode` from server info
- Add AV1 8 bit and 10 bit as options

@OneLiberty 

Tested with QN90A and it seems to work

### CODE REVIEW

**Comment by OneLiberty** [comment]
Hi ! 

Thank you for the PR :D 
Did you check in the debug logs if AV1 was correctly used ? 
I'll need to test it (probably today) before pushing it. 

If anyone else can confirm it working, that would be nice :) 

@henryfa2 can you check that ?

**Comment by HnwT** [comment]
The request seems correct according to the Sunshine logs:
For AV1 10bit
```
a=x-nv-vqos[0].bitStreamFormat:2 

a=x-nv-video[0].dynamicRangeMode:1 

...
[2024:04:07:19:47:33]: Info: Capture format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2024:04:07:19:47:33]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2024:04:07:19:47:33]: Info: Color depth: 10-bit
[2024:04:07:19:47:33]: Info: Color range: [MPEG]
[2024:04:07:19:47:33]: Debug: System tray loop

```

For AV1 8 bit

```
a=x-nv-vqos[0].bitStreamFormat:2 

a=x-nv-video[0].dynamicRangeMode:0 

...
[2024:04:07:19:53:29]: Info: Capture format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2024:04:07:19:53:29]: Info: SDR color coding [Rec. 601]
[2024:04:07:19:53:29]: Info: Color depth: 8-bit
[2024:04:07:19:53:29]: Info: Color range: [MPEG]
```

**Comment by henryfa2** [comment]
@OneLiberty Yeah it is working, and it is a better implementation than mine so let's keep this one.
@HnwT We got a Discord that you can join if you want :) We chat there about development of the app. Link is on the main OneLiberty repo page

**Review by henryfa2 — APPROVED** [review]
Working as intended

**Comment by OneLiberty** [comment]
Doesn't seems to work on my end. 
Stream directly to a blackscreen. 

Could be an issue specific to me tho. 
I'll test a bit more.

EDIT: Well nvm a driver update fixed it... go figure.

**Pull request merged**
